---
- name: Setup Kubernetes controller
  hosts: all
  become: yes
  tasks:
    - name: Test controller provisioning
      debug:
        msg: "Controller provisioning is working"

    - name: Initialize Kubernetes cluster with kubeadm
      command: >
        kubeadm init
        --apiserver-advertise-address=192.168.56.100
        --node-name ctrl
        --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf