---
- name: Setup Kubernetes controller
  hosts: all
  become: yes
  tasks:
    - name: Test controller provisioning
      debug:
        msg: "Controller provisioning is working"

    - name: Initialize Kubernetes cluster with kubeadm
      command: >
        kubeadm init
        --apiserver-advertise-address=192.168.56.100
        --node-name ctrl
        --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create kube directory
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy admin.conf to users kube directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: '0600'

    - name: Copy admin.conf locally
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ playbook_dir }}/../kubeconfig"
        flat: yes

    - name: Create flannel directory
      file:
        path: /flannel
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Download Flannel
      get_url:
        url: https://github.com/flannel-io/flannel/releases/download/v0.26.7/kube-flannel.yml
        dest: /flannel/kube-flannel.yml
        mode: '0644'

    ## Note: the command below was generated with the help of ChatGPT with the prompt: "Modify to add --iface=eth1 to use the correct network interface"
    - name: Modify Flannel manifest to use eth1 interface
      replace:
        path: /flannel/kube-flannel.yml
        regexp: '(- --kube-subnet-mgr)$'
        replace: '\1\n        - --iface=eth1'

    - name: Apply network
      become_user: vagrant
      command: kubectl apply -f /flannel/kube-flannel.yml

    # Helm binary download (faster than apt repository method)
    - name: Check if Helm is already installed
      ansible.builtin.stat:
        path: /usr/local/bin/helm
      register: helm_binary

    - name: Detect system architecture for Helm
      command: dpkg --print-architecture
      register: helm_arch
      changed_when: false
      when: not helm_binary.stat.exists

    - name: Set Helm architecture variable
      set_fact:
        helm_arch_name: "{{ 'arm64' if helm_arch.stdout == 'arm64' else 'amd64' }}"
      when: not helm_binary.stat.exists

    - name: Download Helm binary archive
      ansible.builtin.get_url:
        url: "https://get.helm.sh/helm-v3.19.4-linux-{{ helm_arch_name }}.tar.gz"
        dest: /tmp/helm.tar.gz
        mode: '0644'
      when: not helm_binary.stat.exists

    - name: Extract Helm binary
      ansible.builtin.unarchive:
        src: /tmp/helm.tar.gz
        dest: /tmp/
        remote_src: yes
      when: not helm_binary.stat.exists

    - name: Install Helm to /usr/local/bin
      ansible.builtin.copy:
        src: "/tmp/linux-{{ helm_arch_name }}/helm"
        dest: /usr/local/bin/helm
        remote_src: yes
        mode: '0755'
      when: not helm_binary.stat.exists

    ## Note: the command below was fixed with the help of ChatGPT (which added the "creates" argument)
    - name: Install helm-diff plugin
      become_user: vagrant
      command: helm plugin install https://github.com/databus23/helm-diff
      args:
        creates: /home/vagrant/.local/share/helm/plugins/helm-diff

#    ## Step 19: Generate and save join command
#    - name: Check for existing admin.conf
#      ansible.builtin.stat:
#        path: /etc/kubernetes/admin.conf
#      register: adminconf
#
#    - name: Generate kubeadm join command
#      ansible.builtin.command: kubeadm token create --print-join-command
#      register: kubeadm_join_cmd
#      when: adminconf.stat.exists
#
#    - name: Save join command to shared folder
#      ansible.builtin.copy:
#        dest: /vagrant/join_cmd.sh
#        content: "{{ kubeadm_join_cmd.stdout }}"
#        mode: '0755'
#      when: adminconf.stat.exists
