---
- name: Setup Kubernetes controller
  hosts: all
  become: yes
  tasks:
    - name: Test controller provisioning
      debug:
        msg: "Controller provisioning is working"

    - name: Initialize Kubernetes cluster with kubeadm
      command: >
        kubeadm init
        --apiserver-advertise-address=192.168.56.100
        --node-name ctrl
        --pod-network-cidr=10.244.0.0/16
      args:
        creates: /etc/kubernetes/admin.conf

    - name: Create kube directory
      file:
        path: /home/vagrant/.kube
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Copy admin.conf to users kube directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/vagrant/.kube/config
        remote_src: yes
        owner: vagrant
        group: vagrant
        mode: '0600'

    - name: Copy admin.conf locally
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: "{{ playbook_dir }}/../kubeconfig"
        flat: yes