---
- name: Finalization
  hosts: all
  become: yes
  tasks:
    - name: Create metallb dir
      file:
        path: /metallb
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Download metallb
      get_url:
        url: https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
        dest: /metallb/metallb.yaml
        mode: '0644'

    - name: Apply metallb
      become_user: vagrant
      command: kubectl apply -f /metallb/metallb.yaml


    - name: Wait for metallb to be ready
      become_user: vagrant
      shell: kubectl wait -n metallb-system -l app=metallb,component=controller --for=condition=ready pod --timeout=60s



    - name: Create MetalLB IPAddressPool
      copy:
        dest: /tmp/metallb-ip-pool.yaml
        src: ./local/metallb-ip-pool.yaml

    - name: Apply IPAddressPool
      become_user: vagrant
      command: kubectl apply -f /tmp/metallb-ip-pool.yaml



    - name: Create MetalLB L2Advertisement
      copy:
        dest: /tmp/metallb-l2-advertisement.yaml
        src: ./local/metallb-l2-advertisement.yaml

    - name: Apply L2Advertisement
      become_user: vagrant
      command: kubectl apply -f /tmp/metallb-l2-advertisement.yaml

    - name: Create Istio installation directory
      file:
        path: /opt/istio
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Detect system architecture
      command: dpkg --print-architecture
      register: system_arch
      changed_when: false

    - name: Set Istio architecture variable
      set_fact:
        istio_arch: "{{ 'arm64' if system_arch.stdout == 'arm64' else 'amd64' }}"

    - name: Check if Istio tarball already exists
      stat:
        path: "/opt/istio/istio-1.25.2-linux-{{ istio_arch }}.tar.gz"
      register: istio_tarball

    - name: Download Istio 1.25.2
      get_url:
        url: "https://github.com/istio/istio/releases/download/1.25.2/istio-1.25.2-linux-{{ istio_arch }}.tar.gz"
        dest: "/opt/istio/istio-1.25.2-linux-{{ istio_arch }}.tar.gz"
        mode: '0644'
        owner: vagrant
        group: vagrant
      when: not istio_tarball.stat.exists

    - name: Check if Istio is already unpacked
      stat:
        path: /opt/istio/istio-1.25.2
      register: istio_dir

    - name: Unpack Istio tarball
      unarchive:
        src: "/opt/istio/istio-1.25.2-linux-{{ istio_arch }}.tar.gz"
        dest: /opt/istio/
        remote_src: yes
        owner: vagrant
        group: vagrant
      when: not istio_dir.stat.exists

    - name: Check if istioctl is already in PATH
      stat:
        path: /usr/local/bin/istioctl
      register: istioctl_symlink

    - name: Add istioctl to PATH via symlink
      file:
        src: /opt/istio/istio-1.25.2/bin/istioctl
        dest: /usr/local/bin/istioctl
        state: link
      when: not istioctl_symlink.stat.exists

    - name: Check if Istio is already installed in cluster
      become_user: vagrant
      shell: kubectl get namespace istio-system 2>/dev/null
      register: istio_namespace
      failed_when: false
      changed_when: false

    - name: Add nginx helm repo
      become_user: vagrant
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx

    - name: Deploy nginx chart
      become_user: vagrant
      kubernetes.core.helm:
        name: ingresscontroller
        chart_ref: ingress-nginx/ingress-nginx
        values:
          controller:
            service:
              loadBalancerIp: 192.168.56.90
        release_namespace: nginx
        create_namespace: true

    - name: Wait for NGINX Ingress Controller to be ready
      become_user: vagrant
      shell: |
        kubectl wait --namespace nginx \
          --for=condition=ready pod \
          --selector=app.kubernetes.io/component=controller \
          --timeout=120s

    - name: Add kubernetes dashboard helm repo
      become_user: vagrant
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        repo_url: https://kubernetes.github.io/dashboard

    - name: Deploy kubernetes dashboard
      become_user: vagrant
      kubernetes.core.helm:
        name: kubernetesdashboard
        chart_ref: kubernetes-dashboard/kubernetes-dashboard
        release_namespace: kubernetes-dashboard
        create_namespace: true

    - name: Create admin ServiceAccount
      copy:
        dest: /tmp/admin-serviceaccount.yaml
        src: ./local/admin-serviceaccount.yaml

    - name: Apply admin Serviceaccount
      become_user: vagrant
      command: kubectl apply -f /tmp/admin-serviceaccount.yaml


    - name: Create rolebinding for admin
      copy:
        dest: /tmp/admin-rolebinding.yaml
        src: ./local/admin-rolebinding.yaml


    - name: Apply admin rolebinding
      become_user: vagrant
      command: kubectl apply -f /tmp/admin-rolebinding.yaml


    # We need a self-signed certificate here to run the website with https. With http, modern browsers silently drop the login token, making it appear as if we aren't authrorized.
    # Google gemini LLM generated the "Generate and apply self-signed cert" step based on the issue description and existing playbook. It also generated the "tls" key in the content of the next step.
    - name: Generate and apply self-signed cert
      become_user: vagrant
      shell: |
        openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
          -keyout /tmp/dashboardkey.key \
          -out /tmp/dashboardkey.crt \
          -subj "/CN=dashboard.local"
        
        kubectl create secret tls dashboard-certs \
          --cert=/tmp/dashboardkey.crt \
          --key=/tmp/dashboardkey.key \
          -n kubernetes-dashboard \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Create Ingress for Kubernetes Dashboard
      copy:
        dest: /tmp/dashboard-ingress.yaml
        src: ./local/dashboard-ingress.yaml


    - name: Apply dashboard ingress
      become_user: vagrant
      command: kubectl apply -f /tmp/dashboard-ingress.yaml



    - name: Create IstioOperator configuration for fixed IP
      copy:
        dest: /tmp/istio-operator-config.yaml
        src: ./local/istio-operator-config.yaml
        mode: '0644'

    - name: Install Istio in cluster with fixed IP configuration
      become_user: vagrant
      command: /usr/local/bin/istioctl install -y -f /tmp/istio-operator-config.yaml
      when: istio_namespace.rc != 0
