---
- name: Finalization
  hosts: all
  become: yes
  tasks:
    - name: Create metallb dir
      file:
        path: /metallb
        state: directory
        owner: vagrant
        group: vagrant
        mode: '0755'

    - name: Download metallb
      get_url:
        url: https://raw.githubusercontent.com/metallb/metallb/v0.14.9/config/manifests/metallb-native.yaml
        dest: /metallb/metallb.yaml
        mode: '0644'

    - name: Apply metallb
      become_user: vagrant
      command: kubectl apply -f /metallb/metallb.yaml


    - name: Wait for metallb to be ready
      become_user: vagrant
      shell: kubectl wait -n metallb-system -l app=metallb,component=controller --for=condition=ready pod --timeout=60s



    - name: Create MetalLB IPAddressPool
      copy:
        dest: /tmp/metallb-ip-pool.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: IPAddressPool
          metadata:
            name: first-pool
            namespace: metallb-system
          spec:
            addresses:
              - 192.168.56.90-192.168.56.99

    - name: Apply IPAddressPool
      become_user: vagrant
      command: kubectl apply -f /tmp/metallb-ip-pool.yaml



    - name: Create MetalLB L2Advertisement
      copy:
        dest: /tmp/metallb-l2-advertisement.yaml
        content: |
          apiVersion: metallb.io/v1beta1
          kind: L2Advertisement
          metadata:
            name: example
            namespace: metallb-system
          spec:
            ipAddressPools:
              - first-pool

    - name: Apply L2Advertisement
      become_user: vagrant
      command: kubectl apply -f /tmp/metallb-l2-advertisement.yaml
    
    - name: Add nginx helm repo
      become_user: vagrant
      kubernetes.core.helm_repository:
        name: ingress-nginx
        repo_url: https://kubernetes.github.io/ingress-nginx
    
    - name: Deploy nginx chart
      become_user: vagrant
      kubernetes.core.helm:
        name: ingresscontroller
        chart_ref: ingress-nginx/ingress-nginx
        values:
          controller:
            service:
              loadBalancerIp: 192.168.56.90
        release_namespace: nginx
        create_namespace: true
    
    - name: Add kubernetes dashboard helm repo
      become_user: vagrant
      kubernetes.core.helm_repository:
        name: kubernetes-dashboard
        repo_url: https://kubernetes.github.io/dashboard
    
    - name: Deploy kubernetes dashboard
      become_user: vagrant
      kubernetes.core.helm:
        name: kubernetesdashboard
        chart_ref: kubernetes-dashboard/kubernetes-dashboard
        release_namespace: kubernetes-dashboard
        create_namespace: true

    - name: Create admin ServiceAccount
      copy:
        dest: /tmp/admin-serviceaccount.yaml
        content: |
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: admin-user
            namespace: kubernetes-dashboard
    
    - name: Apply admin Serviceaccount
      become_user: vagrant
      command: kubectl apply -f /tmp/admin-serviceaccount.yaml


    - name: Create rolebinding for admin
      copy:
        dest: /tmp/admin-rolebinding.yaml
        content: |
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: admin-user
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
          - kind: ServiceAccount
            name: admin-user
            namespace: kubernetes-dashboard
    
    - name: Apply admin rolebinding
      become_user: vagrant
      command: kubectl apply -f /tmp/admin-rolebinding.yaml


    # We need a self-signed certificate here to run the website with https. With http, modern browsers silently drop the login token, making it appear as if we aren't authrorized.
    # Google gemini LLM generated the "Generate and apply self-signed cert" step based on the issue description and existing playbook. It also generated the "tls" key in the content of the next step.
    - name: Generate and apply self-signed cert
      become_user: vagrant
      shell: |
        openssl req -x509 -nodes -days 3650 -newkey rsa:2048 \
          -keyout /tmp/dashboardkey.key \
          -out /tmp/dashboardkey.crt \
          -subj "/CN=dashboard.local"
        
        kubectl create secret tls dashboard-certs \
          --cert=/tmp/dashboardkey.crt \
          --key=/tmp/dashboardkey.key \
          -n kubernetes-dashboard \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Create Ingress for Kubernetes Dashboard
      copy:
        dest: /tmp/dashboard-ingress.yaml
        content: |
          apiVersion: networking.k8s.io/v1
          kind: Ingress
          metadata:
            name: kubernetes-dashboard
            namespace: kubernetes-dashboard
            annotations:
              nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          spec:
            ingressClassName: nginx
            tls:
              - hosts:
                  - dashboard.local
                secretName: dashboard-certs
            rules:
              - host: dashboard.local
                http:
                  paths:
                    - path: /
                      pathType: Prefix
                      backend:
                        service:
                          name: kubernetesdashboard-kong-proxy
                          port:
                            number: 443

    - name: Apply dashboard ingress
      become_user: vagrant
      command: kubectl apply -f /tmp/dashboard-ingress.yaml
    


