---
- name: Setup worker nodes
  hosts: all
  become: yes
  tasks:
    - name: Test worker provisioning
      debug:
        msg: "Worker provisioning is working"
    
# Step 18: Get join command from controller
- name: Check if worker already joined the cluster
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet_conf
  
- name: Fetch join command from controller
  ansible.builtin.command: kubeadm token create --print-join-command
  delegate_to: ctrl
  register: join_cmd
  when: not kubelet_conf.stat.exists